import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Test App',
  description: 'Generated by create next app',
}

var array = [];

for(let i = 0; i < 15; i++){
    if (i % 2 == 0){
        array.push('circle');
    } else {
        array.push('x-shape');
    }
}

const myArray = array;


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='lines'>
          <div className='line-1'>
            <div className='shapes'>
            {myArray.map((shape, index) => (
              <div key={index} className={shape}></div>
            ))}
          </div>
          </div>
          <div className='line-2'>
            <div className='shapes'>
            {myArray.map((shape, index) => (
              <div key={index} className={shape}></div>
            ))}
          </div>
          </div>
          <div className='line-3'>
            <div className='shapes'>
            {myArray.map((shape, index) => (
              <div key={index} className={shape}></div>
            ))}
          </div>
          </div>
          <div className='line-4'>
            <div className='shapes'>
            {myArray.map((shape, index) => (
              <div key={index} className={shape}></div>
            ))}
          </div>
          </div>
        </div>
        {children}</body>
    </html>
  )
}
